- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh,Suresh,Raheem,Joseph"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ person | default('Ramesh') }}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ persons | split(',') }}"

  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10HR
        trainer: Chakradhar
    ansible.builtin.debug:
      msg: "Course Info: {{ course | dict2items }}"

  - name: convert list into map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10HR'}
      - {'key': 'trainer', 'value': 'Chakradhar'}
    ansible.builtin.debug:
      msg: "Course Info: {{ course | items2dict }}"

  - name: convert into uppercase
    vars:
      name: "CHAKRADHAR K"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"

  - name: convert into lowercase
    vars:
      name: "CHAKRADHAR K"
    ansible.builtin.debug:
      msg: "Hello {{ name | lower }}"

  - name: check IP address is valid or not
    vars:
     ip: "300.567.980.789"
     ansible.builtin.debug:
      msg: "is {{ ip | ansible.utils.ipaddr }}"